#!/usr/bin/env bash
# test-index-identical.sh — regen_index output stays byte-identical to the committed
# golden index (generated by the pre-BL-686 per-item implementation) on a fixture
# with active, blocked, awaiting, deferred, archived items, companions and odd fields.
# Layer: shell integration; the index is a pure function of the tree, so the golden diff
# is the boundary. Also pins the stale-index message of close-item.sh.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
SCRIPTS="$HERE/../scripts"
PASS=0 FAIL=0
ok()  { printf '  ok: %s\n' "$1"; PASS=$((PASS+1)); }
bad() { printf '  FAIL: %s\n' "$1" >&2; FAIL=$((FAIL+1)); }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
bash "$HERE/build-index-fixture.sh" "$TMP"
cd "$TMP"
bash "$SCRIPTS/register-item.sh" --reindex >/dev/null
sed 's/^\*\*Updated:\*\* .*/**Updated:** DATE/' .context/backlog/00-index.md >"$TMP/actual.md"
if diff "$HERE/fixtures/expected-00-index.md" "$TMP/actual.md" >"$TMP/diff.txt"; then
  ok "index is byte-identical to the golden"
else bad "index differs from golden"; head -20 "$TMP/diff.txt" >&2; fi

# close-item.sh: a failing reindex must say the index is stale (it used to be silent).
mkdir -p "$TMP/s/skills/backlog/scripts"; cp "$SCRIPTS"/*.sh "$TMP/s/skills/backlog/scripts/"
ln -s "$HERE/../../conventions" "$TMP/s/skills/conventions"
printf '#!/usr/bin/env bash\nexit 1\n' >"$TMP/s/skills/backlog/scripts/register-item.sh"
err="$(bash "$TMP/s/skills/backlog/scripts/close-item.sh" BL-003 --status done 2>&1 >/dev/null || true)"
if grep -q "archived but the index is stale" <<<"$err" && grep -q -- "--reindex" <<<"$err"; then
  ok "failed reindex prints the stale-index line"
else bad "no stale-index line on failed reindex: $err"; fi

# A nonconforming id makes --reindex exit 1 AFTER it wrote the index: close-item must keep
# main's exit code (1), let the guard's stderr through and NOT claim the index is stale.
T2="$(mktemp -d)"; bash "$HERE/build-index-fixture.sh" "$T2"
sed -i.bak 's/^id: BL-031$/id: BL-20260538/' "$T2/.context/backlog/_deferred/2026-08-11-d2.md"
cd "$T2"
rc=0; err="$(bash "$SCRIPTS/close-item.sh" BL-003 --status done 2>&1 >/dev/null)" || rc=$?
if [[ $rc -eq 1 ]] && ! grep -q "index is stale" <<<"$err" && grep -q "nonconforming id BL-20260538" <<<"$err" \
   && grep -q "2026-09-01-c-p2.md" <(sed -n '/^## Closed/,$p' .context/backlog/00-index.md); then
  ok "guard failure after a written index: exit 1, no stale line, item in Closed"
else bad "guard-failure close misreported (rc=$rc): $err"; fi
rm -rf "$T2"

printf 'index-identical: %d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
