#!/usr/bin/env python3
"""derive_glyph_widths.py — regenerate `diagram_widths.py` (a DEV tool, not runtime).

    pip install fonttools            # derivation step only; runtime is stdlib
    python3 derive_glyph_widths.py SFNS.ttf Roboto.ttf DejaVuSans.ttf \\
        LiberationSans-Regular.ttf selawk.ttf > diagram_widths.py

For every character in CHARS the table keeps the WIDEST advance (in 1/1000 em,
rounded up) across the regular weight of the fonts the kit's `--sans` stack
(`-apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif`) can
resolve to. A box sized from it fits the label in whichever font the reader has.

Sources of the committed table (advance widths from each font's `hmtx`; a
variable font is instantiated at wght 400, wdth 100, opsz 17):

  SF Pro Text   macOS -apple-system.  /System/Library/Fonts/SFNS.ttf on macOS 26
                (Darwin 25.6), the system UI font file, instantiated at opsz 17 (Text).
  Segoe UI      Windows.  Proprietary and not redistributable, so measured on
                Selawik 1.01 (`selawk.ttf`, Selawik_Release.zip at
                https://github.com/microsoft/Selawik/releases/tag/1.01), which
                Microsoft ships as the metrically compatible open Segoe UI.
  Roboto        Android / ChromeOS / many Linux system-ui:
                https://github.com/google/fonts/blob/main/ofl/roboto/Roboto[wdth,wght].ttf
  DejaVu Sans   Linux sans-serif fallback: dejavu-fonts 2.37,
                https://github.com/dejavu-fonts/dejavu-fonts/releases/tag/version_2_37
  Liberation Sans  Linux sans-serif fallback (Arial metrics): liberation-fonts
                2.1.5, https://github.com/liberationfonts/liberation-fonts/releases/tag/2.1.5

A font lacking a character (Roboto and Selawik have no U+2192) simply does not
vote on it; a character NO font has is left out and `text_width` falls back to
its own estimate.
"""
import math
import sys

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

# A variable font is measured at the Regular instance a label is drawn in:
# weight 400, width 100, and SF's optical size at max(17, FS) = 17: the Text
# cut, wider than SF's default opsz 28 (Display), and the safe side for a box.
AXES = {"wght": 400, "wdth": 100, "opsz": 17}


def load(path):
    f = TTFont(path)
    if "fvar" in f:
        keep = {a.axisTag: AXES[a.axisTag] for a in f["fvar"].axes
                if a.axisTag in AXES}
        f = instantiateVariableFont(f, keep)
    return f

CHARS = ("".join(chr(c) for c in range(32, 127))
         + "áéíóúñüÁÉÍÓÚÑÜàèìòùâêîôûäëïöçÀÈÌÒÙÂÊÎÔÛÄËÏÖÇãõÃÕ"
         + "¿¡—–·→←↑↓↔⇒✓≠∞…“”‘’«»°×≥≤€")


def main(paths):
    fonts = [load(p) for p in paths]
    table = {}
    for ch in CHARS:
        adv = []
        for f in fonts:
            cmap = f.getBestCmap()
            if ord(ch) in cmap:
                adv.append(f["hmtx"][cmap[ord(ch)]][0] * 1000.0
                           / f["head"].unitsPerEm)
        if adv:
            table[ch] = int(math.ceil(max(adv)))
    print('"""diagram_widths.py — GENERATED by derive_glyph_widths.py; do not edit.')
    print()
    print("Widest regular-weight advance per character, in 1/1000 em, across the")
    print("fonts of the kit\'s `--sans` stack. Sources: derive_glyph_widths.py.")
    print('"""')
    print()
    print("GLYPH_WIDTHS = {")
    for ch, w in table.items():
        print("    %s: %d," % (repr(ch), w))
    print("}")


if __name__ == "__main__":
    main(sys.argv[1:])
