#!/usr/bin/env python3
"""graph_svg.py — the `::: graph` renderer: DOT in, a kit-themed SVG out.

Rung 2 of the figure ladder (plan `2026-09-24-deterministic-figures`, Phase 5).
The layout is Graphviz's (`dot -Tsvg`); this module only runs it and turns its
output into a figure that themes like every other kit figure. Graphviz is an
OPTIONAL dependency: with no `dot` on PATH the build fails with the install
line — never an empty figure, never a figure drawn some other way.

Why Graphviz and not a post-processed tool: its `class` attribute reaches the
SVG verbatim (`a [class=acc]` -> `<g class="node acc">`, verified 2026-09-24 on
graphviz 16.1.0), so the kit's `figure svg .acc/.flg/.mut` rules colour a node
or an edge with no id-map and no guessing. `research/2026-09-23-deterministic-
diagrams-prior-art.md` is the survey.

What this module does to Graphviz's SVG, and nothing else:

  * keeps only the `<svg>` element: the XML declaration, the doctype and every
    comment go (the version is kept, in the figure's own comment);
  * the root keeps its `viewBox` and loses `width`/`height`, like `chart` and
    `diagram` — `components.css` sizes a figure's svg;
  * the white background polygon goes, and so does every `id=` and `<title>`:
    ids like `node1` repeat across two graphs on one page, and a `<title>`
    is the DOT node NAME, not its label;
  * Graphviz's default colour, `black`, becomes `currentColor`; `none` stays.
    ANY other colour is refused: a graph's colour comes from `class=` and
    nothing else, because a literal colour is right in one theme at most;
  * every `<text>` gets `fill="currentColor"`, so a label is the colour of
    its class (or the page's ink) in both themes;
  * `font-family="monospace"` (the default this module passes to `dot`, so
    Graphviz sizes boxes with a monospace advance) becomes the kit's `--mono`
    stack, spelled out as `diagram_svg.MONO` is;
  * the root group's `scale(1 1) rotate(0)` identity is dropped, leaving the
    plain `translate`, so `check_artifact`'s svg-text rule measures the labels
    instead of skipping them as transformed.

Refused, each by name: a class other than `acc`/`mut`/`flg` (Graphviz's own
`graph`/`node`/`edge`/`cluster` stay), a link (`URL=`/`href=`), an image, a
`style=` attribute, a font other than the kit's `--mono`, and — checked on the
PARSED svg against a whitelist — any other element or attribute: Graphviz does
not escape `"` inside `fontname`, so a DOT can inject `<script>` or `onclick=`.
A processing instruction is refused too. The page then carries the vetted tree
RE-SERIALISED, never Graphviz's bytes (BL-451): XML reads `<?x ><script>…?>`
as one instruction, HTML reads `<?x >` as a comment and runs the script, and
only a headless-Chrome probe showed it. `dot` gets `TIMEOUT` seconds.
"""

import html
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, "dash"))
sys.path.insert(0, _HERE)
from _shell import esc                             # noqa: E402
import diagram_layout as dl                        # noqa: E402
import diagram_svg                                 # noqa: E402

INSTALL = ("install Graphviz: `brew install graphviz` (macOS) or "
           "`apt install graphviz` (Debian/Ubuntu)")
KIT_CLASSES = ("acc", "mut", "flg")
GENERATOR_CLASSES = ("graph", "node", "edge", "cluster")
# Defaults passed on the command line; a DOT that sets its own wins.
FONT = "monospace"
DEFAULTS = ["-Gfontname=" + FONT, "-Nfontname=" + FONT, "-Efontname=" + FONT,
            "-Gfontsize=%g" % dl.TITLE_FS, "-Nfontsize=%g" % dl.FS,
            "-Efontsize=%g" % dl.TITLE_FS]

VERSION = re.compile(r"Generated by graphviz version (\S+)")
SVG_EL = re.compile(r"<svg\b[^>]*>.*</svg>", re.S)
VIEWBOX = re.compile(r'viewBox="([^"]*)"')
DOT_LINE = re.compile(r"\bline (\d+)")
NODE_G = re.compile(r'<g class="(?:node|cluster)\b[^"]*">(.*?)</g>', re.S)
TEXT_EL = re.compile(r"<text\b[^>]*>(.*?)</text>", re.S)
EDGE_G = re.compile(r'<g class="edge\b[^"]*">(.*?)</g>', re.S)
# Seconds `dot` may run. A figure that takes longer is not a figure.
TIMEOUT = 30

# The whole vocabulary a cleaned graph may carry, checked on the PARSED svg
# (review finding 1): Graphviz does not escape `"` inside `fontname`, so a DOT
# can write an element or an `on*=` attribute into its own output. Anything
# outside these two lists — script, foreignObject, a, image, style, href, src,
# any on* — is refused by name. `{…}space` is `xml:space`.
SVG_NS = "{http://www.w3.org/2000/svg}"
ELEMENTS = ("svg", "g", "path", "polygon", "polyline", "ellipse", "text")
ATTRS = ("viewBox", "role", "class", "transform", "fill", "stroke",
         "stroke-width", "stroke-dasharray", "points", "d", "cx", "cy", "rx",
         "ry", "x", "y", "text-anchor", "font-family", "font-size",
         "font-weight", "font-style", "{http://www.w3.org/XML/1998/namespace}space")


class GraphError(Exception):
    """The DOT cannot become a kit figure. The message says why."""


def dot_path():
    return shutil.which("dot")


def render(dot_text, first_line=None):
    """`(svg, version)` for a DOT source, or raise `GraphError`.

    `first_line` is the spec line of the DOT's first line: Graphviz's own
    "syntax error in line N" is then followed by the spec line it means.
    """
    exe = dot_path()
    if not exe:
        raise GraphError("`graph` needs Graphviz's `dot` on PATH and there is "
                         "none — " + INSTALL)
    try:
        proc = subprocess.run([exe, "-Tsvg"] + DEFAULTS,
                              input=dot_text.encode("utf-8"),
                              capture_output=True, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        raise GraphError("Graphviz did not finish within %d s — a graph that "
                         "takes longer to lay out is too big for a figure"
                         % TIMEOUT) from None
    if proc.returncode != 0:
        said = proc.stderr.decode("utf-8", "replace").strip()
        if first_line is not None:
            said = DOT_LINE.sub(
                lambda m: "line %s (spec line %d)"
                % (m.group(1), first_line + int(m.group(1)) - 1), said)
        raise GraphError("Graphviz refused the DOT: " + (said or "exit %d"
                                                         % proc.returncode))
    out = proc.stdout.decode("utf-8")
    m = VERSION.search(out)
    return clean(out), (m.group(1) if m else "unknown")


def clean(raw):
    """Graphviz's SVG document -> one kit-themed `<svg>` element."""
    m = SVG_EL.search(raw)
    if not m:
        raise GraphError("Graphviz produced no <svg> element")
    svg = m.group(0)
    for bad, why in (("<a ", "a link (URL= or href=)"),
                     ("<image", "an image (image=)"),
                     (" style=", "a style= attribute"),
                     ("<?", "a processing instruction (`<?`), which HTML reads "
                            "as a comment ending at the first `>`")):
        if bad in svg:
            raise GraphError("the DOT asks for %s, which a kit graph does not "
                             "carry" % why)
    svg = re.sub(r"<!--.*?-->\n?", "", svg, flags=re.S)
    svg = re.sub(r"<title>.*?</title>\n?", "", svg, flags=re.S)
    svg = re.sub(r'<polygon fill="white" stroke="none"[^>]*/>\n?', "", svg,
                 count=1)
    svg = re.sub(r'\s+id="[^"]*"', "", svg)
    svg = svg.replace('transform="scale(1 1) rotate(0) ', 'transform="')

    vb = VIEWBOX.search(svg.split(">", 1)[0])
    if not vb:
        raise GraphError("Graphviz's <svg> has no viewBox")
    svg = ('<svg viewBox="%s" xmlns="http://www.w3.org/2000/svg" role="img">'
           % vb.group(1)) + svg.split(">", 1)[1]
    root = _vet(svg)
    # BL-451: the page gets the vetted TREE, re-serialised — never Graphviz's
    # bytes, which an HTML parser can read differently from the XML parse.
    out = []
    _write(root, out)
    return "".join(out)


def _vet(svg):
    """Parse the cleaned svg, refuse anything outside the whitelist, and
    theme it in place: every check runs on the parsed attributes, so a
    single-quoted `class='x'` is read like a double-quoted one."""
    try:
        root = ET.fromstring(svg)
    except ET.ParseError as exc:
        raise GraphError("Graphviz's output is not well-formed SVG (%s) — a "
                         "DOT attribute wrote markup into it" % exc) from None
    for el in root.iter():
        tag = _local(el)
        if tag not in ELEMENTS:
            raise GraphError("the DOT puts a <%s> element in the figure, which "
                             "a kit graph does not carry" % tag)
        for key, value in el.attrib.items():
            if key not in ATTRS:
                raise GraphError("the DOT puts a %s= attribute on a <%s>, "
                                 "which a kit graph does not carry"
                                 % (key, tag))
    for el in root.iter():
        for tok in el.attrib.get("class", "").split():
            if tok not in GENERATOR_CLASSES + KIT_CLASSES:
                raise GraphError(
                    "class=%r is not a kit class — a graph node or edge takes "
                    "class=%s" % (tok, ", ".join(KIT_CLASSES)))
        for attr in ("fill", "stroke"):
            value = el.attrib.get(attr)
            if value is None or value == "none":
                continue
            if value != "black":
                raise GraphError(
                    "the DOT sets a colour (%s=\"%s\") — a graph takes its "
                    "colour from class=acc, mut or flg, which theme in light "
                    "and dark; a literal colour is right in one theme at most"
                    % (attr, value))
            el.set(attr, "currentColor")
        if _local(el) == "text" and "fill" not in el.attrib:
            el.attrib = dict([("fill", "currentColor")] + list(el.attrib.items()))
    # Fonts last, so an injected element or attribute is what gets named.
    for el in root.iter():
        font = el.attrib.get("font-family")
        if font == FONT:
            el.set("font-family", diagram_svg.MONO)
        elif font is not None:
            raise GraphError(
                "the DOT sets a font (fontname=%r) — a graph is drawn in the "
                "kit's --mono stack, the one Graphviz sizes its boxes for"
                % font)
    return root


def _local(el):
    return el.tag[len(SVG_NS):] if el.tag.startswith(SVG_NS) else el.tag


def _write(el, out):
    """One vetted element as markup: every attribute double-quoted and
    escaped, every text escaped — the same string to HTML and to XML."""
    tag = _local(el)
    out.append("<" + tag)
    if tag == "svg":
        out.append(' xmlns="http://www.w3.org/2000/svg"')
    for key, value in el.attrib.items():
        if key.startswith("{"):
            key = "xml:" + key.split("}", 1)[1]
        out.append(' %s="%s"' % (key, html.escape(value, quote=True)))
    if not len(el) and not el.text:
        out.append("/>")
        return
    out.append(">" + html.escape(el.text or "", quote=False))
    for child in el:
        _write(child, out)
        out.append(html.escape(child.tail or "", quote=False))
    out.append("</%s>" % tag)


def edges(svg):
    """`{"solid": n, "dashed": m}`: every drawn edge, by stroke kind.

    An edge is dashed when its path carries a dash array (`style=dashed` or
    `dotted`). Invisible edges are not drawn and not counted.
    """
    out = {"solid": 0, "dashed": 0}
    for m in EDGE_G.finditer(svg):
        out["dashed" if "stroke-dasharray" in m.group(1) else "solid"] += 1
    return out


def labels(svg):
    """The text of every node and cluster, in document order.

    A multi-line label (several `<text>` in one node) is its lines joined by
    one space. Edge labels are not node labels and are not returned. A node's
    `xlabel` is drawn inside the node's group, so it JOINS that node's label
    ("Main EXTRA"): a census that does not record it will not match, which
    fails closed.
    """
    out = []
    for m in NODE_G.finditer(svg):
        lines = [html.unescape(t).strip() for t in TEXT_EL.findall(m.group(1))]
        out.append(" ".join(ln for ln in lines if ln))
    return out


def figure(svg, version, title="", classes="", ident=""):
    """The whole block: `<figure>`, the Graphviz version, the SVG, the caption.

    The id is carried as `id=` and nothing else — `chart_svg.figure` says why a
    `data-id=` on a figure is read as a decision.
    """
    head = "<figure"
    if ident:
        head += ' id="%s"' % esc(ident)
    if classes:
        head += ' class="%s"' % esc(classes)
    out = [head + ">", "<!-- graph: graphviz %s -->" % esc(version), svg]
    if title:
        out.append("<figcaption>%s</figcaption>" % esc(title))
    out.append("</figure>")
    return "\n".join(out)
