#!/usr/bin/env bash
# backfill-indexes.sh — generate the plans/audits roll-up index (00-index.md) for
# projects that predate the index feature. Cross-skill onboarding tool: delegates
# to aidex-plan/scripts/reindex-plans.sh and aidex-audit/scripts/reindex-audits.sh.
#
# SAFE BY DEFAULT: a hand-made 00-index.md (one WITHOUT the "Auto-generated by"
# marker) is skipped, not clobbered — pass --force to overwrite it. Generating a
# missing index, or refreshing an already auto-generated one, is purely additive.
#
# Usage:
#   backfill-indexes.sh                      # current project only (walks up to .context)
#   backfill-indexes.sh --all <projects-root># every immediate subdir of root with .context
#   backfill-indexes.sh --project <dir>      # one explicit project dir
#
# Options:
#   --refresh    also regenerate indexes that are already auto-generated (default:
#                only create MISSING ones; auto-gen ones are left as-is)
#   --force      overwrite hand-made indexes too (default: skip + warn)
#   --dry-run    report what would happen; write nothing
#
# Exit 0 always (a skipped hand-made index is not an error); warnings go to stderr.

set -euo pipefail

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  C_GREEN=$'\033[32m' C_YELLOW=$'\033[33m' C_BLUE=$'\033[34m' C_DIM=$'\033[2m' C_BOLD=$'\033[1m' C_RESET=$'\033[0m'
else C_GREEN='' C_YELLOW='' C_BLUE='' C_DIM='' C_BOLD='' C_RESET=''; fi
info() { printf '%s%s%s\n' "$C_BLUE" "$*" "$C_RESET" >&2; }
ok()   { printf '%s%s%s\n' "$C_GREEN" "$*" "$C_RESET" >&2; }
warn() { printf '%s%s%s\n' "$C_YELLOW" "$*" "$C_RESET" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
RP="$SCRIPT_DIR/../../aidex-plan/scripts/reindex-plans.sh"
RA="$SCRIPT_DIR/../../aidex-audit/scripts/reindex-audits.sh"

MODE=self ROOT="" PROJECT="" REFRESH=0 FORCE=0 DRY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)     MODE=all; ROOT="$2"; shift 2 ;;
    --project) MODE=project; PROJECT="$2"; shift 2 ;;
    --refresh) REFRESH=1; shift ;;
    --force)   FORCE=1; shift ;;
    --dry-run) DRY=1; shift ;;
    -h|--help) sed -n '2,/^$/p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
done

find_project_root() {
  local dir; dir="$(pwd -P)"
  while [[ "$dir" != "/" ]]; do
    [[ -d "$dir/.context" ]] && { printf '%s\n' "$dir"; return 0; }
    dir="$(dirname "$dir")"
  done
  return 1
}

# Classify an index file: missing | auto | manual
classify_index() {
  local idx="$1"
  [[ -f "$idx" ]] || { echo missing; return; }
  grep -q 'Auto-generated by' "$idx" && echo auto || echo manual
}

declare -i n_created=0 n_refreshed=0 n_skipped=0

# Backfill one artifact (plans|audits) for one project dir.
backfill_one() {
  local proj="$1" kind="$2" reindexer="$3"
  local dir="$proj/.context/$kind"
  [[ -d "$dir" ]] || return 0
  [[ -x "$reindexer" ]] || { warn "  $kind: reindexer missing ($reindexer)"; return 0; }

  local idx="$dir/00-index.md" cls; cls="$(classify_index "$idx")"
  case "$cls" in
    manual)
      if [[ $FORCE -eq 0 ]]; then
        warn "  $kind: SKIP hand-made 00-index.md (use --force to overwrite) — $idx"
        n_skipped+=1; return 0
      fi
      warn "  $kind: --force overwriting hand-made 00-index.md"
      ;;
    auto)
      if [[ $REFRESH -eq 0 ]]; then
        printf '%s  %s: already auto-generated (use --refresh to regenerate)%s\n' "$C_DIM" "$kind" "$C_RESET" >&2
        return 0
      fi
      ;;
  esac

  if [[ $DRY -eq 1 ]]; then
    info "  $kind: would ${cls/missing/create} ${cls/auto/refresh} 00-index.md (dry-run)"
    return 0
  fi
  ( cd "$proj" && NO_COLOR="${NO_COLOR:-}" bash "$reindexer" >/dev/null 2>&1 )
  if [[ "$cls" == "missing" ]]; then ok "  $kind: created 00-index.md"; n_created+=1
  else ok "  $kind: refreshed 00-index.md"; n_refreshed+=1; fi
}

backfill_project() {
  local proj="$1"
  [[ -d "$proj/.context" ]] || return 0
  printf '%s%s%s\n' "$C_BOLD" "${proj/#$HOME/~}" "$C_RESET" >&2
  backfill_one "$proj" plans  "$RP"
  backfill_one "$proj" audits "$RA"
}

case "$MODE" in
  self)
    proj="$(find_project_root)" || { warn "no .context found from $(pwd) — run inside a project or use --all/--project"; exit 0; }
    backfill_project "$proj"
    ;;
  project)
    [[ -d "$PROJECT" ]] || { warn "no such dir: $PROJECT"; exit 0; }
    backfill_project "$(cd "$PROJECT" && pwd -P)"
    ;;
  all)
    [[ -d "$ROOT" ]] || { warn "no such root: $ROOT"; exit 0; }
    shopt -s nullglob
    for d in "$ROOT"/*/; do
      [[ -d "$d/.context" ]] && backfill_project "${d%/}"
    done
    shopt -u nullglob
    ;;
esac

printf '\n%s%d created · %d refreshed · %d hand-made skipped%s\n' \
  "$C_BOLD" "$n_created" "$n_refreshed" "$n_skipped" "$C_RESET" >&2
