#!/usr/bin/env bash
# test-backfill-indexes.sh — backfill creates missing indexes, skips hand-made
# ones by default, and overwrites them only with --force.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
BF="$SCRIPT_DIR/backfill-indexes.sh"

pass=0; fail=0
check() { if eval "$2"; then echo "  ok: $1"; pass=$((pass+1)); else echo "  FAIL: $1"; fail=$((fail+1)); fi; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
ROOT="$TMP/projects"; mkdir -p "$ROOT"

# proj A: plans dir, no index → should be created
mkdir -p "$ROOT/projA/.context/plans"
printf -- '---\ntitle: "P"\nstatus: open\ncreated: 2026-06-01\nupdated: 2026-06-01\n---\n# P\n' \
  > "$ROOT/projA/.context/plans/2026-06-01-p.md"

# proj B: audits dir with a run + inventory, no index → should be created
mkdir -p "$ROOT/projB/.context/audits/20260601-run"
printf -- '---\ntitle: "R"\nstatus: doing\ncreated: 2026-06-01\nmethodology: ux-audit\n---\n# R\n' \
  > "$ROOT/projB/.context/audits/20260601-run/index.md"
printf '| ID | Type | Module | Summary | Status | Severity | First Seen | Last Updated | Audit Runs | Escalated To | Notes |\n| X-1 | bug | m | s | open | P1 | 2026-06-01 | 2026-06-01 | 20260601-run | — | n |\n' \
  > "$ROOT/projB/.context/audits/00-inventory.md"

# proj C: hand-made plans index (no auto-gen marker) → must be skipped
mkdir -p "$ROOT/projC/.context/plans"
printf -- '---\ntitle: Plans\n---\n# Plans\n\nCurated by hand. Do not lose this.\n' \
  > "$ROOT/projC/.context/plans/00-index.md"

echo "== dry-run --all =="
NO_COLOR=1 bash "$BF" --all "$ROOT" --dry-run >/dev/null 2>&1
check "dry-run wrote nothing for A" '[[ ! -f "$ROOT/projA/.context/plans/00-index.md" ]]'

echo "== real --all (default: skip hand-made) =="
out="$(NO_COLOR=1 bash "$BF" --all "$ROOT" 2>&1)"
check "projA plans index created"   '[[ -f "$ROOT/projA/.context/plans/00-index.md" ]] && grep -q "Auto-generated by" "$ROOT/projA/.context/plans/00-index.md"'
check "projB audits index created"  '[[ -f "$ROOT/projB/.context/audits/00-index.md" ]] && grep -q "1 open / 1 findings" "$ROOT/projB/.context/audits/00-index.md"'
check "projC hand-made preserved"   'grep -q "Curated by hand" "$ROOT/projC/.context/plans/00-index.md"'
check "summary reports a skip"      'printf "%s" "$out" | grep -q "hand-made skipped"'

echo "== --force overwrites hand-made =="
NO_COLOR=1 bash "$BF" --project "$ROOT/projC" --force >/dev/null 2>&1
check "projC now auto-generated"    'grep -q "Auto-generated by" "$ROOT/projC/.context/plans/00-index.md"'
check "curated content gone"        '! grep -q "Curated by hand" "$ROOT/projC/.context/plans/00-index.md"'

echo ""
echo "backfill-indexes: $pass passed, $fail failed"
[[ $fail -eq 0 ]]
